# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

USER_LIB_PATH = $(realpath ../lib)
OBJDIR = ../build
BOARD_TAG = diecimila
BOARD_SUB = atmega328
include ../arduino-makefile/Arduino.mk
